name = input('Enter ur name: ')
last_name = input('Enter ur last name: ')
age = input('Enter ur age: ')
country = input('Enter ur country: ')
f_food = input('Enter ur favorite food: ')
f_car = input('Enter ur favorite car: ')
city = input('Enter ur city: ')
f_color = input('Enter ur favorite color: ')
f_sport = input('Enter ur favorite sport: ')
hobby = input('Enter ur hobby: ')
f_film = input('Enter ur favorite film: ')
print("Hello, friends! My name is " + name + " " + last_name + ". I'm " + age + ". I'm from " + country + " and live in " + city + ". My favorite color is " + f_color + ". My favorite food is " + f_food + ". My favorite film is " + f_film + ". My favorite car brand is " + f_car + ". My favorite sport is " + f_sport + " and my hobby is " + hobby + ".")
